/* Generated By:JJTree: Do not edit this line. ASTheader_section.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.part21.parser;

public
@SuppressWarnings("all")
class ASTheader_section extends SimpleNode {
  public ASTheader_section(int id) {
    super(id);
  }

  public ASTheader_section(ClearTextReader p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ClearTextReaderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8efebd8af3b923e9dc8b6dea620cb1e8 (do not edit this line) */
