/* Generated By:JavaCC: Do not edit this line. ClearTextReaderTreeConstants.java Version 5.0 */
package org.ifc4emf.part21.parser;

@SuppressWarnings("all")
public interface ClearTextReaderTreeConstants
{
  public int JJTEXCHANGE_FILE = 0;
  public int JJTHEADER_SECTION = 1;
  public int JJTHEADER_ENTITY_LIST = 2;
  public int JJTHEADER_ENTITY = 3;
  public int JJTVOID = 4;
  public int JJTTYPED_PARAMETER = 5;
  public int JJTUNTYPED_PARAMETER = 6;
  public int JJTOMITTED_PARAMETER = 7;
  public int JJTLIST = 8;
  public int JJTDATA_SECTION = 9;
  public int JJTENTITY_INSTANCE_LIST = 10;
  public int JJTENTITY_INSTANCE = 11;
  public int JJTSCOPE = 12;
  public int JJTEXPORT_LIST = 13;
  public int JJTSIMPLE_RECORD = 14;
  public int JJTSUBSUPER_RECORD = 15;
  public int JJTSIMPLE_RECORD_LIST = 16;
  public int JJTSYNTAX = 17;


  public String[] jjtNodeName = {
    "exchange_file",
    "header_section",
    "header_entity_list",
    "header_entity",
    "void",
    "typed_parameter",
    "untyped_parameter",
    "omitted_parameter",
    "list",
    "data_section",
    "entity_instance_list",
    "entity_instance",
    "scope",
    "export_list",
    "simple_record",
    "subsuper_record",
    "simple_record_list",
    "syntax",
  };
}
/* JavaCC - OriginalChecksum=16586b286a0f7a8620b15da509187b23 (do not edit this line) */
