/* Generated By:JJTree: Do not edit this line. ASTsubsuper_record.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.part21.parser;

public
@SuppressWarnings("all")
class ASTsubsuper_record extends SimpleNode {
  public ASTsubsuper_record(int id) {
    super(id);
  }

  public ASTsubsuper_record(ClearTextReader p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ClearTextReaderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=77c5a3e8cb6dddadb4a5d4620e587e6f (do not edit this line) */
