/* Generated By:JJTree: Do not edit this line. ASTtyped_parameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.part21.parser;

public
@SuppressWarnings("all")
class ASTtyped_parameter extends SimpleNode {
  public ASTtyped_parameter(int id) {
    super(id);
  }

  public ASTtyped_parameter(ClearTextReader p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ClearTextReaderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4114b4efc47bbf7ad8e2f452a62d98dc (do not edit this line) */
