/* Generated By:JavaCC: Do not edit this line. ClearTextReaderVisitor.java Version 5.0 */
package org.ifc4emf.part21.parser;

@SuppressWarnings("all")
public interface ClearTextReaderVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTexchange_file node, Object data);
  public Object visit(ASTheader_section node, Object data);
  public Object visit(ASTheader_entity_list node, Object data);
  public Object visit(ASTheader_entity node, Object data);
  public Object visit(ASTtyped_parameter node, Object data);
  public Object visit(ASTuntyped_parameter node, Object data);
  public Object visit(ASTomitted_parameter node, Object data);
  public Object visit(ASTlist node, Object data);
  public Object visit(ASTdata_section node, Object data);
  public Object visit(ASTentity_instance_list node, Object data);
  public Object visit(ASTentity_instance node, Object data);
  public Object visit(ASTscope node, Object data);
  public Object visit(ASTexport_list node, Object data);
  public Object visit(ASTsimple_record node, Object data);
  public Object visit(ASTsubsuper_record node, Object data);
  public Object visit(ASTsimple_record_list node, Object data);
  public Object visit(ASTsyntax node, Object data);
}
/* JavaCC - OriginalChecksum=446a0473be23992a0fa286613a358ee7 (do not edit this line) */
