/* Generated By:JJTree: Do not edit this line. ASTaggregate_initializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTaggregate_initializer extends SimpleNode {
  public ASTaggregate_initializer(int id) {
    super(id);
  }

  public ASTaggregate_initializer(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=46b1f05f9d6f97cff2ffa6b0bafb7bd1 (do not edit this line) */
