/* Generated By:JJTree: Do not edit this line. ASTbuilt_in_function.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTbuilt_in_function extends SimpleNode {
  public ASTbuilt_in_function(int id) {
    super(id);
  }

  public ASTbuilt_in_function(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b62aac30d5c3b7a13bc9dc55182cb4ff (do not edit this line) */
