/* Generated By:JJTree: Do not edit this line. ASTgeneral_aggregation_types.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTgeneral_aggregation_types extends SimpleNode {
  public ASTgeneral_aggregation_types(int id) {
    super(id);
  }

  public ASTgeneral_aggregation_types(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0c41e17dccce79bd9157a529ac8140c (do not edit this line) */
