/* Generated By:JJTree: Do not edit this line. ASTreferenced_attribute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTreferenced_attribute extends SimpleNode {
  public ASTreferenced_attribute(int id) {
    super(id);
  }

  public ASTreferenced_attribute(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=48e56e9ce178f0cfcf3b1d55267a35b4 (do not edit this line) */
