/* Generated By:JavaCC: Do not edit this line. ExpressParserTreeConstants.java Version 5.0 */
package org.ifc4emf.metamodel.express.parser;

@SuppressWarnings("all")
public interface ExpressParserTreeConstants
{
  public int JJTSIMPLE_ID = 0;
  public int JJTATTRIBUTE_REF = 1;
  public int JJTCONSTANT_REF = 2;
  public int JJTENTITY_REF = 3;
  public int JJTENUMERATION_REF = 4;
  public int JJTFUNCTION_REF = 5;
  public int JJTPARAMETER_REF = 6;
  public int JJTPROCEDURE_REF = 7;
  public int JJTSCHEMA_REF = 8;
  public int JJTTYPE_LABEL_REF = 9;
  public int JJTTYPE_REF = 10;
  public int JJTVARIABLE_REF = 11;
  public int JJTABSTRACT_SUPERTYPE_DECLARATION = 12;
  public int JJTACTUAL_PARAMETER_LIST = 13;
  public int JJTADD_LIKE_OP = 14;
  public int JJTAGGREGATE_INITIALIZER = 15;
  public int JJTAGGREGATE_SOURCE = 16;
  public int JJTAGGREGATE_TYPE = 17;
  public int JJTAGGREGATION_TYPES = 18;
  public int JJTALGORITHM_HEAD = 19;
  public int JJTALIAS_STMT = 20;
  public int JJTARRAY_TYPE = 21;
  public int JJTASSIGNMENT_STMT = 22;
  public int JJTATTRIBUTE_DECL = 23;
  public int JJTATTRIBUTE_ID = 24;
  public int JJTATTRIBUTE_QUALIFIER = 25;
  public int JJTBAG_TYPE = 26;
  public int JJTBASE_TYPE = 27;
  public int JJTBINARY_TYPE = 28;
  public int JJTBOOLEAN_TYPE = 29;
  public int JJTBOUND_1 = 30;
  public int JJTBOUND_2 = 31;
  public int JJTBOUND_SPEC = 32;
  public int JJTBUILT_IN_CONSTANT = 33;
  public int JJTBUILT_IN_FUNCTION = 34;
  public int JJTBUILT_IN_PROCEDURE = 35;
  public int JJTCASE_ACTION = 36;
  public int JJTCASE_LABEL = 37;
  public int JJTCASE_STMT = 38;
  public int JJTCOMPOUND_STMT = 39;
  public int JJTCONSTANT_BODY = 40;
  public int JJTCONSTANT_DECL = 41;
  public int JJTCONSTANT_FACTOR = 42;
  public int JJTCONSTANT_ID = 43;
  public int JJTCONSTRUCTED_TYPES = 44;
  public int JJTDECLARATION = 45;
  public int JJTDERIVED_ATTR = 46;
  public int JJTDERIVE_CLAUSE = 47;
  public int JJTDOMAIN_RULE = 48;
  public int JJTELEMENT = 49;
  public int JJTENTITY_BODY = 50;
  public int JJTENTITY_CONSTRUCTOR = 51;
  public int JJTENTITY_DECL = 52;
  public int JJTENTITY_HEAD = 53;
  public int JJTENTITY_ID = 54;
  public int JJTENUMERATION_ID = 55;
  public int JJTENUMERATION_REFERENCE = 56;
  public int JJTENUMERATION_TYPE = 57;
  public int JJTESCAPE_STMT = 58;
  public int JJTEXPLICIT_ATTR = 59;
  public int JJTEXPRESSION = 60;
  public int JJTFACTOR = 61;
  public int JJTFORMAL_PARAMETER = 62;
  public int JJTFUNCTION_CALL = 63;
  public int JJTFUNCTION_DECL = 64;
  public int JJTFUNCTION_HEAD = 65;
  public int JJTFUNCTION_ID = 66;
  public int JJTGENERALIZED_TYPES = 67;
  public int JJTGENERAL_AGGREGATION_TYPES = 68;
  public int JJTGENERAL_ARRAY_TYPE = 69;
  public int JJTGENERAL_BAG_TYPE = 70;
  public int JJTGENERAL_LIST_TYPE = 71;
  public int JJTGENERAL_REF = 72;
  public int JJTGENERAL_SET_TYPE = 73;
  public int JJTGENERIC_TYPE = 74;
  public int JJTGROUP_QUALIFIER = 75;
  public int JJTIF_STMT = 76;
  public int JJTINCREMENT = 77;
  public int JJTINCREMENT_CONTROL = 78;
  public int JJTINDEX = 79;
  public int JJTINDEX_1 = 80;
  public int JJTINDEX_2 = 81;
  public int JJTINDEX_QUALIFIER = 82;
  public int JJTINTEGER_TYPE = 83;
  public int JJTINTERFACE_SPECIFICATION = 84;
  public int JJTINTERVAL = 85;
  public int JJTINTERVAL_HIGH = 86;
  public int JJTINTERVAL_ITEM = 87;
  public int JJTINTERVAL_LOW = 88;
  public int JJTINTERVAL_OP = 89;
  public int JJTINVERSE_ATTR = 90;
  public int JJTINVERSE_CLAUSE = 91;
  public int JJTLABEL = 92;
  public int JJTLIST_TYPE = 93;
  public int JJTLITERAL = 94;
  public int JJTLOCAL_DECL = 95;
  public int JJTLOCAL_VARIABLE = 96;
  public int JJTLOGICAL_EXPRESSION = 97;
  public int JJTLOGICAL_LITERAL = 98;
  public int JJTLOGICAL_TYPE = 99;
  public int JJTMULTIPLICATION_LIKE_OP = 100;
  public int JJTNAMED_TYPES = 101;
  public int JJTNAMED_TYPE_OR_RENAME = 102;
  public int JJTNULL_STMT = 103;
  public int JJTNUMBER_TYPE = 104;
  public int JJTNUMERIC_EXPRESSION = 105;
  public int JJTONE_OF = 106;
  public int JJTPARAMETER = 107;
  public int JJTPARAMETER_ID = 108;
  public int JJTPARAMETER_TYPE = 109;
  public int JJTPOPULATION = 110;
  public int JJTPRECISION_SPEC = 111;
  public int JJTPRIMARY = 112;
  public int JJTPROCEDURE_CALL_STMT = 113;
  public int JJTPROCEDURE_DECL = 114;
  public int JJTPROCEDURE_HEAD = 115;
  public int JJTPROCEDURE_ID = 116;
  public int JJTQUALIFIABLE_FACTOR = 117;
  public int JJTQUALIFIED_ATTRIBUTE = 118;
  public int JJTQUALIFIER = 119;
  public int JJTQUERY_EXPRESSION = 120;
  public int JJTREAL_TYPE = 121;
  public int JJTREFERENCED_ATTRIBUTE = 122;
  public int JJTREFERENCE_CLAUSE = 123;
  public int JJTREL_OP = 124;
  public int JJTREL_OP_EXTENDED = 125;
  public int JJTRENAME_ID = 126;
  public int JJTREPEAT_CONTROL = 127;
  public int JJTREPEAT_STMT = 128;
  public int JJTREPETITION = 129;
  public int JJTRESOURCE_OR_RENAME = 130;
  public int JJTRESOURCE_REF = 131;
  public int JJTRETURN_STMT = 132;
  public int JJTRULE_DECL = 133;
  public int JJTRULE_HEAD = 134;
  public int JJTRULE_ID = 135;
  public int JJTSCHEMA_BODY = 136;
  public int JJTSCHEMA_DECL = 137;
  public int JJTSCHEMA_ID = 138;
  public int JJTSELECTOR = 139;
  public int JJTSELECT_TYPE = 140;
  public int JJTSET_TYPE = 141;
  public int JJTSIGN = 142;
  public int JJTSIMPLE_EXPRESSION = 143;
  public int JJTSIMPLE_FACTOR = 144;
  public int JJTSIMPLE_TYPES = 145;
  public int JJTSKIP_STMT = 146;
  public int JJTSTMT = 147;
  public int JJTSTRING_LITERAL = 148;
  public int JJTSTRING_TYPE = 149;
  public int JJTSUBSUPER = 150;
  public int JJTSUBTYPE_CONSTRAINT = 151;
  public int JJTSUBTYPE_DECLARATION = 152;
  public int JJTSUPERTYPE_CONSTRAINT = 153;
  public int JJTSUPERTYPE_EXPRESSION = 154;
  public int JJTSUPERTYPE_FACTOR = 155;
  public int JJTSUPERTYPE_RULE = 156;
  public int JJTSUPERTYPE_TERM = 157;
  public int JJTSYNTAX = 158;
  public int JJTTERM = 159;
  public int JJTTYPE_DECL = 160;
  public int JJTTYPE_ID = 161;
  public int JJTTYPE_LABEL = 162;
  public int JJTTYPE_LABEL_ID = 163;
  public int JJTUNARY_OP = 164;
  public int JJTUNDERLYING_TYPE = 165;
  public int JJTUNIQUE_CLAUSE = 166;
  public int JJTUNIQUE_RULE = 167;
  public int JJTUNTIL_CONTROL = 168;
  public int JJTUSE_CLAUSE = 169;
  public int JJTVARIABLE_ID = 170;
  public int JJTWHERE_CLAUSE = 171;
  public int JJTWHILE_CONTROL = 172;
  public int JJTWIDTH = 173;
  public int JJTWIDTH_SPEC = 174;


  public String[] jjtNodeName = {
    "simple_id",
    "attribute_ref",
    "constant_ref",
    "entity_ref",
    "enumeration_ref",
    "function_ref",
    "parameter_ref",
    "procedure_ref",
    "schema_ref",
    "type_label_ref",
    "type_ref",
    "variable_ref",
    "abstract_supertype_declaration",
    "actual_parameter_list",
    "add_like_op",
    "aggregate_initializer",
    "aggregate_source",
    "aggregate_type",
    "aggregation_types",
    "algorithm_head",
    "alias_stmt",
    "array_type",
    "assignment_stmt",
    "attribute_decl",
    "attribute_id",
    "attribute_qualifier",
    "bag_type",
    "base_type",
    "binary_type",
    "boolean_type",
    "bound_1",
    "bound_2",
    "bound_spec",
    "built_in_constant",
    "built_in_function",
    "built_in_procedure",
    "case_action",
    "case_label",
    "case_stmt",
    "compound_stmt",
    "constant_body",
    "constant_decl",
    "constant_factor",
    "constant_id",
    "constructed_types",
    "declaration",
    "derived_attr",
    "derive_clause",
    "domain_rule",
    "element",
    "entity_body",
    "entity_constructor",
    "entity_decl",
    "entity_head",
    "entity_id",
    "enumeration_id",
    "enumeration_reference",
    "enumeration_type",
    "escape_stmt",
    "explicit_attr",
    "expression",
    "factor",
    "formal_parameter",
    "function_call",
    "function_decl",
    "function_head",
    "function_id",
    "generalized_types",
    "general_aggregation_types",
    "general_array_type",
    "general_bag_type",
    "general_list_type",
    "general_ref",
    "general_set_type",
    "generic_type",
    "group_qualifier",
    "if_stmt",
    "increment",
    "increment_control",
    "index",
    "index_1",
    "index_2",
    "index_qualifier",
    "integer_type",
    "interface_specification",
    "interval",
    "interval_high",
    "interval_item",
    "interval_low",
    "interval_op",
    "inverse_attr",
    "inverse_clause",
    "label",
    "list_type",
    "literal",
    "local_decl",
    "local_variable",
    "logical_expression",
    "logical_literal",
    "logical_type",
    "multiplication_like_op",
    "named_types",
    "named_type_or_rename",
    "null_stmt",
    "number_type",
    "numeric_expression",
    "one_of",
    "parameter",
    "parameter_id",
    "parameter_type",
    "population",
    "precision_spec",
    "primary",
    "procedure_call_stmt",
    "procedure_decl",
    "procedure_head",
    "procedure_id",
    "qualifiable_factor",
    "qualified_attribute",
    "qualifier",
    "query_expression",
    "real_type",
    "referenced_attribute",
    "reference_clause",
    "rel_op",
    "rel_op_extended",
    "rename_id",
    "repeat_control",
    "repeat_stmt",
    "repetition",
    "resource_or_rename",
    "resource_ref",
    "return_stmt",
    "rule_decl",
    "rule_head",
    "rule_id",
    "schema_body",
    "schema_decl",
    "schema_id",
    "selector",
    "select_type",
    "set_type",
    "sign",
    "simple_expression",
    "simple_factor",
    "simple_types",
    "skip_stmt",
    "stmt",
    "string_literal",
    "string_type",
    "subsuper",
    "subtype_constraint",
    "subtype_declaration",
    "supertype_constraint",
    "supertype_expression",
    "supertype_factor",
    "supertype_rule",
    "supertype_term",
    "syntax",
    "term",
    "type_decl",
    "type_id",
    "type_label",
    "type_label_id",
    "unary_op",
    "underlying_type",
    "unique_clause",
    "unique_rule",
    "until_control",
    "use_clause",
    "variable_id",
    "where_clause",
    "while_control",
    "width",
    "width_spec",
  };
}
/* JavaCC - OriginalChecksum=a241e6704dd7b53acc9ae49c1362b4a8 (do not edit this line) */
