/* Generated By:JJTree: Do not edit this line. ASTabstract_supertype_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTabstract_supertype_declaration extends SimpleNode {
  public ASTabstract_supertype_declaration(int id) {
    super(id);
  }

  public ASTabstract_supertype_declaration(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7179a559554c6f827091052f8a28f26f (do not edit this line) */
