/* Generated By:JJTree: Do not edit this line. ASTmultiplication_like_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTmultiplication_like_op extends SimpleNode {
  public ASTmultiplication_like_op(int id) {
    super(id);
  }

  public ASTmultiplication_like_op(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49845cf26ec4c067c03c1f91950304ed (do not edit this line) */
