/* Generated By:JJTree: Do not edit this line. ASTnamed_type_or_rename.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTnamed_type_or_rename extends SimpleNode {
  public ASTnamed_type_or_rename(int id) {
    super(id);
  }

  public ASTnamed_type_or_rename(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3aa2be21405ef0e154c6b5f0fa5e9f36 (do not edit this line) */
