/* Generated By:JJTree: Do not edit this line. ASTexchange_file.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.part21.parser;

public
@SuppressWarnings("all")
class ASTexchange_file extends SimpleNode {
  public ASTexchange_file(int id) {
    super(id);
  }

  public ASTexchange_file(ClearTextReader p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ClearTextReaderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa45c3d2eb2877e51b8b97e4e9fc73a8 (do not edit this line) */
