/* Generated By:JJTree: Do not edit this line. ASTbuilt_in_procedure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.metamodel.express.parser;

public
@SuppressWarnings("all")
class ASTbuilt_in_procedure extends SimpleNode {
  public ASTbuilt_in_procedure(int id) {
    super(id);
  }

  public ASTbuilt_in_procedure(ExpressParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=84bba1ef5e38f82e60ec75a162bb1cd2 (do not edit this line) */
