/* Generated By:JJTree: Do not edit this line. ASTdata_section.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.part21.parser;

public
@SuppressWarnings("all")
class ASTdata_section extends SimpleNode {
  public ASTdata_section(int id) {
    super(id);
  }

  public ASTdata_section(ClearTextReader p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ClearTextReaderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b49835785fbeb495cd7cdb0cd109664d (do not edit this line) */
