/* Generated By:JJTree: Do not edit this line. ASTsimple_record_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.ifc4emf.part21.parser;

public
@SuppressWarnings("all")
class ASTsimple_record_list extends SimpleNode {
  public ASTsimple_record_list(int id) {
    super(id);
  }

  public ASTsimple_record_list(ClearTextReader p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ClearTextReaderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=44536d8b5d2f07fe4dfc73ca7a0e3431 (do not edit this line) */
